-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 02:37:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beautyplanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beautyplanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beautyplanner` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `beautyplanner` ;

-- -----------------------------------------------------
-- Table `beautyplanner`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beautyplanner`.`users` ;

CREATE TABLE IF NOT EXISTS `beautyplanner`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(50) NOT NULL,
  `pass_user` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_user` VARCHAR(15) NOT NULL,
  `role_user` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautyplanner`.`sms_reminders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beautyplanner`.`sms_reminders` ;

CREATE TABLE IF NOT EXISTS `beautyplanner`.`sms_reminders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visit_id` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `message` TEXT(300) NOT NULL,
  `post_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `visit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautyplanner`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beautyplanner`.`visits` ;

CREATE TABLE IF NOT EXISTS `beautyplanner`.`visits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `facility_id` INT NOT NULL,
  `date_and_time_of_visit` DATETIME NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `facility_id`, `date_and_time_of_visit`),
  CONSTRAINT `przy`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`sms_reminders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uzy`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautyplanner`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beautyplanner`.`services` ;

CREATE TABLE IF NOT EXISTS `beautyplanner`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `facility_id` INT NOT NULL,
  `nazwa` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `minute_duration` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `facility_id`),
  CONSTRAINT `wizyty`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`visits` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beautyplanner`.`facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beautyplanner`.`facilities` ;

CREATE TABLE IF NOT EXISTS `beautyplanner`.`facilities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_facilities` VARCHAR(100) NOT NULL,
  `adress_facilities` VARCHAR(255) NOT NULL,
  `phone_facilities` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `uz`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pla`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`services` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `wizy`
    FOREIGN KEY (`id`)
    REFERENCES `beautyplanner`.`visits` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
